### ISSUE TITLE
Type convert issue blocking the script running

### ISSUE THREAD

**Issue by OpenBanboo** [gplhegde/theano-xnor-net#3]
Dear Developer,

I tried to use your code to reproduce the result. However, I keep meeting this TensorType convert issue. I was wandering whether it's because the the Theano changed something?

After loading the data:
('Trainset shape = ', (40000, 3, 32, 32), (40000, 10))
('Valset shape = ', (10000, 3, 32, 32), (10000, 10))
('Testset shape = ', (10000, 3, 32, 32), (10000, 10))
Constructed symbolic output
Constructed symbolic training loss
Defining the update process...
Traceback (most recent call last):
  File "cifar10_train.py", line 182, in <module>
    W_grads = bnn_utils.compute_grads(loss,net)
  File "/Users/fanglin/Documents/XNOR-Net/Xnor-Net-Theano/train/external/bnn_utils.py", line 59, in compute_grads
    grads.append(theano.grad(loss, wrt=layer.Wb))
  File "/Library/Python/2.7/site-packages/theano/gradient.py", line 555, in grad
    grad_dict, wrt, cost_name)
  File "/Library/Python/2.7/site-packages/theano/gradient.py", line 1317, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/Library/Python/2.7/site-packages/theano/gradient.py", line 1272, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/Library/Python/2.7/site-packages/theano/gradient.py", line 967, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/Library/Python/2.7/site-packages/theano/gradient.py", line 1108, in access_term_cache
    new_output_grads)
  File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 711, in L_op
    return self.grad(inputs, output_grads)
  File "/Library/Python/2.7/site-packages/theano/tensor/nnet/abstract_conv.py", line 1704, in grad
    d_bottom = bottom.type.filter_variable(d_bottom)
  File "/Library/Python/2.7/site-packages/theano/tensor/type.py", line 235, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(float32, 4D) (of Variable AbstractConv2d_gradInputs{convdim=2, border_mode=(1, 1), subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None), filter_dilation=(1, 1)}.0) into Type TensorType(float64, 4D). You can try to manually convert AbstractConv2d_gradInputs{convdim=2, border_mode=(1, 1), subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None), filter_dilation=(1, 1)}.0 into a TensorType(float64, 4D).

Thanks!

**Comment by gplhegde** [comment]
I suspect this is due to the default float type of theano. Set the fefault float type to float32 in theanorc file and try again. Thanks

**Comment by OpenBanboo** [comment]
That's true, it's running now! Thanks!

**Comment by OpenBanboo** [comment]
Attach for people new to theano like me:
To add default float type to float32:
1. vi ~/.theanorc
2. Copy and paste:
floatX = float32

**Comment by gplhegde** [comment]
Glad to know that you got it working !
